# Remove version as it's obsolete
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:

  # formr.org application (Configure in etc/formr/apache.conf and formr_app/formr/config/settings.php)

  formr_app:
    build:
      context: ./formr_app
      dockerfile: Dockerfile
    container_name: formr_app
    hostname: formr_app
    environment:
      - TZ=${TIMEZONE}
      - FORMR_TAG=${FORMR_TAG} #required
      - FORMR_APACHE_CONFIG=${FORMR_APACHE_CONFIG}
      - XDEBUG_MODE=debug,develop
      - XDEBUG_CONFIG="client_host=host.docker.internal client_port=9003 idekey=VSCODE"
      - PHP_IDE_CONFIG="serverName=Docker"
    volumes:
      - ./formr_app:/formr
      - ./formr_app/apache/sites-enabled:/etc/apache2/sites-enabled/ #apache vhost conf
      - ./formr_app/formr.php.ini:/usr/local/etc/php/conf.d/custom.php.ini # php.ini
      - ./certs/formr.cert.pem:/etc/ssl/certs/formr.cert.pem:ro
      - ./certs/formr.key.pem:/etc/ssl/private/formr.key.pem:ro
    restart: unless-stopped
    depends_on:
      formr_db:
        condition: service_healthy
      opencpu:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    networks:
      - all
    logging: *default-logging
#    healthcheck:
#      test: ["CMD", "curl", "-f", "-k", "https://localhost/"]
#      interval: 10s
#      timeout: 5s
#      retries: 3


  # mysql database (Configure in formr_app/formr/config/settings.php)

  formr_db:
    image: mariadb:11.7.2
    container_name: formr_db
    hostname: formr_db
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_HOST=${MARIADB_ROOT_HOST}
      - TZ=${TIMEZONE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/dbinitial:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - all
    logging: *default-logging
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  formrmailqueue:
    build:
      context: php_daemon
      dockerfile: Dockerfile
    container_name: formrmailqueue
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./formr_app/formr:/formr
    working_dir: /formr
    command: php bin/queue.php -t Email
    restart: always
    depends_on:
      formr_app:
        condition: service_started
    networks:
      - all

  formrsessionqueue:
    build:
      context: php_daemon
      dockerfile: Dockerfile
    container_name: formrsessionqueue
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./formr_app/formr:/formr
    working_dir: /formr
    command: php bin/queue.php -t UnitSession
    restart: always
    depends_on:
      formr_app:
        condition: service_started
    networks:
      - all

  opencpu:
    build:
      context: opencpu
      dockerfile: Dockerfile
    container_name: opencpu
    hostname: opencpu
    volumes:
      - ./opencpu/conf/server.conf:/etc/opencpu/server.conf
      - ./opencpu/conf/server.conf.d:/etc/opencpu/server.conf.d
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "8080:80"
    networks:
      - all
    restart: always
    logging: *default-logging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ocpu/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  all:
    driver: bridge
    name: all
